# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ed9d4a59e535037573d719994e1cc1eb2f1d464239977db77448b2825e2ad53687a3b43494c1da1061617e67671d6145396693e5eb50c38e52662af82791ad5

test:
  secret_key_base: 21516e3ca69e0d52a51b3244ec271ac51f1dcc226ea4f76df8656f8b1f7829a5ead03b3cfb8b088c3f650f644aa0906458b6b3f69305f9047bac48055d4416b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
